version: '3.9'
services: 
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=crm_db
    volumes:
      - ./db/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - "8080:80" 
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql